# Generated by Django 5.0.7 on 2024-07-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverurl',
            field=models.TextField(default='images/bookcover.jpg'),
            preserve_default=False,
        ),
    ]
