# Generated by Django 5.0.7 on 2024-07-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_coverurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
