# Generated by Django 5.0.7 on 2024-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='current',
            field=models.TextField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
