# Generated by Django 5.0.7 on 2024-08-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_review_current_book_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='current',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='stripe_token',
            new_name='book_title',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='dated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='promo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='statue',
            field=models.CharField(default='Available', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='available', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(default='q23refasd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
