# Generated by Django 5.0.7 on 2024-08-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_current_book_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='currency',
            new_name='current',
        ),
    ]
