# Generated by Django 5.0.7 on 2024-08-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_currency_book_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='book_title',
        ),
        migrations.AddField(
            model_name='transactions',
            name='book',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
