# Generated by Django 5.0.7 on 2024-08-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_address_remove_transactions_book_transactions_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition_description',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='product_dimensions',
            field=models.CharField(default='4', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default='2024-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='6', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='sales_rank',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
