# Generated by Django 5.0.7 on 2024-08-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_book_edition_description_book_isbn_book_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(),
        ),
    ]
